server:
  port: 8081
  servlet:
    context-path: /webui



security:
  sso:
    login-path: /login
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8080/javasso/oauth/token
      userAuthorizationUri: http://localhost:8080/javasso/oauth/authorize
      scope:
      - user_info
      #- profile
      grant-type: authorization_code
    resource:
      userInfoUri: http://localhost:8080/javasso/user/me
      userNameAttribite: name

spring:
  datasource:
    name: postgresqlDataSource
    url:  jdbc:postgresql://192.168.200.149:5432/gisdata
    username: gisdata
    password: gisdata

  security:
    oauth2:
      client:
        registration:
          ataoge:
            provider: ataoge
            client-id: SampleClientId
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/ataoge"
            scope:
            - user_info
            client-name: ATAOGE
        provider:
          ataoge:
            authorization-uri: http://localhost:8080/javasso/oauth/authorize
            token-uri: http://localhost:8080/javasso/oauth/token
            user-info-uri: http://localhost:8080/javasso/user/me
            user-name-attribute: name


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false